[workspace]
resolver = "2"
members = [
    "uwasm",
    "uwasm-custom",
    "uwasm-perf",
    "uwasm-test",
    "uwasm-uc",
]

[workspace.lints.clippy]
new_without_default = "allow"

[profile.release]
debug = true
